plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT' apply false
    id 'net.darkhax.curseforgegradle' version "${curseforgegradle_version}" apply false
}

subprojects {
    configurations.all {
        resolutionStrategy {
            cacheChangingModulesFor 60, 'seconds'
            cacheDynamicVersionsFor 60, 'seconds'
        }
    }
    // Pass the raw project version string as an extra property to each subproject
    // since the version property will be overwritten by the complete version string
    ext {
        rawVersion = project.version
    }
}
