# Project
version=1.0.1
java_version=25

# Metadata
mod_name=Ribbits
mod_full_name=Ribbits
mod_id=ribbits
# This is only for the JAR manifest. Full credits are included in fabric.mod.json and project docs.
mod_author=YUNGNICKYOUNG
mod_description=Adds cute little frogs to swamps!
mod_credits=Thank you to everyone who supported the official Ribbits plushie campaign!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.ribbits
mc_version=26.1.2
mc_version_range_fabric=>=26.1 <26.2

# CurseForge Publishing
curseforgegradle_version=1.1.15
compatible_versions=26.1,26.1.1,26.1.2
curseforge_project_id=1555275
debug_publish=false

# Fabric
fabric_version=0.149.1
fabric_loader_version=0.19.2
clothconfig_version_fabric=26.1.154
modmenu_version_fabric=18.0.0-beta.1
geckolib_version_fabric=5.5.1

# Credentials for publishing. Gets overwritten by global gradle.properties.
curseforgeApiKey=""

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
